name: Deploy to Azure

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Restore workloads
        run: dotnet workload restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Web project
        run: dotnet publish Daggerheart-Helper.Web/Daggerheart-Helper.Web.csproj -c Release -o publish

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: daggerheart-helper
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: publish
